name: 'Lock inactive closed threads'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  lock:
    name: "Lock"
    runs-on: ubuntu-latest
    steps:
      -
        name: "Lock"
        uses: dessant/lock-threads@v3.0.0
        with:
          issue-inactive-days: '31'
          add-issue-labels: 'archived'
          issue-comment: >
            This issue has been automatically locked since there
            has not been any recent activity after it was closed.
            Please open a new issue for related bugs.
          issue-lock-reason: 'resolved'

          pr-inactive-days: '90'
          exclude-any-pr-labels: 'wip'
          add-pr-labels: 'archived'
          pr-comment: >
            This pull request has been automatically locked since there
            has not been any recent activity after it was closed.
            Please open a new issue for related bugs.
          pr-lock-reason: 'resolved'
